# run_migrations = true
listen_addr = ":3000"
data_dir = "/Some/Dir"
username = "admin" # Username of the first user
initial_password = "admin" # Initial Password for user (should change after first login)
jwt_secret = "" # Example: openssl rand -base64 32
sonarr_url = "http://localhost:8989" # Address of the sonarr
sonarr_api_key = "some api key" # The api key for the sonarr instance
